global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['localhost:3000']

  - job_name: 'frontend'
    static_configs:
      - targets: ['localhost:3001']

  - job_name: 'mongodb'
    static_configs:
      - targets: ['localhost:27017']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']